-- FOREIGN TABLE: public.tbl_receivables

-- DROP FOREIGN TABLE IF EXISTS public.tbl_receivables;

CREATE FOREIGN TABLE IF NOT EXISTS public.tbl_receivables(
    id bigint,
    customeraccountid bigint,
    customermobilenumber character varying(15) COLLATE pg_catalog."default",
    customeraccountname character varying(200) COLLATE pg_catalog."default",
    hsn_sac_number character varying(30) COLLATE pg_catalog."default",
    numberofemployees integer,
    netamountreceived numeric(18,2),
    servicechargepercent numeric(18,2),
    servicechargeamount numeric(18,2),
    gstmode character varying(40) COLLATE pg_catalog."default",
    sgstpercent numeric(18,2),
    sgstamount numeric(18,2),
    cgstpercent numeric(18,2),
    cgstamount numeric(18,2),
    igstpercent numeric(18,2),
    igstamount numeric(18,2),
    netamount numeric(18,2),
    dateofinitiation date,
    dateofreceiving date,
    source character varying(50) COLLATE pg_catalog."default",
    is_verified bit(1),
    verifiedbyempcode bigint,
    verifiedon timestamp without time zone,
    verifiedbyip character varying(200) COLLATE pg_catalog."default",
    transactionid character varying(100) COLLATE pg_catalog."default",
    status character varying(20) COLLATE pg_catalog."default",
    invoiceno character varying(100) COLLATE pg_catalog."default",
    invoicedt date,
    invoicetype character varying(100) COLLATE pg_catalog."default",
    orderno character varying(100) COLLATE pg_catalog."default",
    orderdate date,
    referenceno character varying(100) COLLATE pg_catalog."default",
    contractids character varying(400) COLLATE pg_catalog."default",
    contractname character varying(200) COLLATE pg_catalog."default",
    service_name character varying(100) COLLATE pg_catalog."default",
    paymentmethod character varying(100) COLLATE pg_catalog."default",
    created_by bigint,
    createdon timestamp without time zone,
    createdbyip character varying(200) COLLATE pg_catalog."default",
    mdified_by bigint,
    mdified_on timestamp without time zone,
    mdified_byip character varying(200) COLLATE pg_catalog."default",
    isactive bit(1),
    recordpushedtotally bit(1),
    recordpushedtotallyon timestamp without time zone,
    packagename character varying(100) COLLATE pg_catalog."default",
    json_response text COLLATE pg_catalog."default",
    tallyinvoiceid bigint,
    tallymasterid character varying(30) COLLATE pg_catalog."default",
    receiptpushedtotally bit(1),
    receiptpushedtotallyon timestamp without time zone,
    appsource character varying(30) COLLATE pg_catalog."default",
    senttogateway character varying(1) COLLATE pg_catalog."default",
    opscrmticketgenerated character varying(1) COLLATE pg_catalog."default",
    tallyinvoicenumber character varying(100) COLLATE pg_catalog."default",
    financial_year character varying(9) COLLATE pg_catalog."default",
    tranexpiryminutes integer,
    paymentmethodupdatetime timestamp without time zone,
    credit_applicable character varying(1) COLLATE pg_catalog."default",
    credit_percent numeric(18,2),
    credit_used character varying(1) COLLATE pg_catalog."default",
    credit_used_date timestamp without time zone,
    creditmonth integer,
    credityear integer,
    remarks character varying(100) COLLATE pg_catalog."default",
    product_type character varying(200) COLLATE pg_catalog."default",
    entrytype character varying(10) COLLATE pg_catalog."default",
    dfm_invoicenumber_y_n character varying(1) COLLATE pg_catalog."default",
    payout_mode_type character varying(10) COLLATE pg_catalog."default",
    receipt_amount numeric(18,4),
    tds_amount numeric(18,4),
    adjustment_amount numeric(18,2),
    adjustment_tallyinvoicenumber character varying(100) COLLATE pg_catalog."default",
    excess_amount numeric(18,4),
    istaxincluded character varying(1) COLLATE pg_catalog."default",
    narration character varying(1000) COLLATE pg_catalog."default",
    servicedescline2 character varying(200) COLLATE pg_catalog."default",
    servicedescline3 character varying(200) COLLATE pg_catalog."default",
    servicedescline4 character varying(200) COLLATE pg_catalog."default",
    servicedescline5 character varying(200) COLLATE pg_catalog."default",
    servicedescline6 character varying(200) COLLATE pg_catalog."default",
    servicedescline7 character varying(200) COLLATE pg_catalog."default",
    servicedescline8 character varying(200) COLLATE pg_catalog."default",
    servicedescline9 character varying(200) COLLATE pg_catalog."default",
    servicedescline10 character varying(200) COLLATE pg_catalog."default",
    consignee_address character varying(500) COLLATE pg_catalog."default",
    consignee_state character varying(100) COLLATE pg_catalog."default",
    consignee_city character varying(100) COLLATE pg_catalog."default",
    consignee_pincode character varying(100) COLLATE pg_catalog."default",
    billtype character varying(30) COLLATE pg_catalog."default",
    invoicemonth integer,
    invoiceyear integer,
    other_deductions numeric(18,2),
    final_customeramountpaid numeric(18,2),
    billing_address character varying(1000) COLLATE pg_catalog."default",
    billing_state character varying(100) COLLATE pg_catalog."default",
    pfadmincharges numeric(18,2),
    invoicefrequency character varying(500) COLLATE pg_catalog."default",
    subscriptionfrom date,
    subscriptionto date,
    billdate date,
    is_bill_outstanding character varying(1) COLLATE pg_catalog."default"
)
    SERVER hubapp_db_fw
    OPTIONS (schema_name 'public', table_name 'vw_receivables');

ALTER FOREIGN TABLE public.tbl_receivables
    OWNER TO payrollingdb;