-- Table: public.paymentadvice

-- DROP TABLE IF EXISTS public.paymentadvice;

CREATE TABLE IF NOT EXISTS public.paymentadvice
(
    fnfarrivalstatus text COLLATE pg_catalog."default",
    mprmonth integer NOT NULL,
    mpryear integer NOT NULL,
    is_paused character varying(20) COLLATE pg_catalog."default",
    emp_id integer,
    mon text COLLATE pg_catalog."default",
    dateofjoining text COLLATE pg_catalog."default",
    esinumber character varying(17) COLLATE pg_catalog."default",
    posting_department character varying(1000) COLLATE pg_catalog."default",
    projectname text COLLATE pg_catalog."default",
    contractno text COLLATE pg_catalog."default",
    contractcategory text COLLATE pg_catalog."default",
    contracttype text COLLATE pg_catalog."default",
    activeinbatch text COLLATE pg_catalog."default",
    appointment_status_id integer,
    remark text COLLATE pg_catalog."default",
    lockstatus text COLLATE pg_catalog."default",
    is_account_verified bit(1),
    isesiexceptionalcase text COLLATE pg_catalog."default",
    esicexceptionmessage character varying(150) COLLATE pg_catalog."default",
    emp_code bigint NOT NULL,
    subunit integer,
    dateofleaving text COLLATE pg_catalog."default",
    totalleavetaken double precision,
    emp_name character varying(100) COLLATE pg_catalog."default",
    post_offered text COLLATE pg_catalog."default",
    emp_address character varying(500) COLLATE pg_catalog."default",
    email character varying(100) COLLATE pg_catalog."default",
    mobilenum character varying(15) COLLATE pg_catalog."default",
    pancard text COLLATE pg_catalog."default",
    gender character(10) COLLATE pg_catalog."default",
    dateofbirth text COLLATE pg_catalog."default",
    fathername character varying(100) COLLATE pg_catalog."default",
    residential_address character varying(300) COLLATE pg_catalog."default",
    pfnumber character varying(30) COLLATE pg_catalog."default",
    uannumber character varying(30) COLLATE pg_catalog."default",
    lossofpay double precision,
    paiddays double precision,
    monthdays integer,
    ratebasic numeric(18,2),
    ratehra numeric(18,2),
    rateconv double precision,
    ratemedical double precision,
    ratespecialallowance numeric(18,2),
    fixedallowancestotalrate numeric(18,2),
    basic double precision,
    hra double precision,
    conv double precision,
    medical double precision,
    specialallowance double precision,
    fixedallowancestotal double precision,
    ratebasic_arr double precision,
    ratehra_arr double precision,
    rateconv_arr double precision,
    ratemedical_arr double precision,
    ratespecialallowance_arr double precision,
    fixedallowancestotalrate_arr double precision,
    incentive double precision,
    refund numeric,
    grossearning double precision,
    epf double precision,
    vpf double precision,
    employeeesirate double precision,
    tds double precision,
    loan double precision,
    lwf numeric(18,2),
    insurance numeric,
    mobile double precision,
    advance double precision,
    other double precision,
    grossdeduction double precision,
    netpay double precision,
    ac_1 double precision,
    ac_10 double precision,
    ac_2 double precision,
    ac21 double precision,
    employeresirate double precision,
    lwfcontr integer,
    ews numeric,
    gratuity numeric,
    recordtype text COLLATE pg_catalog."default",
    govt_bonus_opted character varying(1) COLLATE pg_catalog."default",
    govt_bonus_amt double precision,
    is_special_category character varying(1) COLLATE pg_catalog."default",
    ct2 double precision,
    batch_no character varying(150) COLLATE pg_catalog."default" NOT NULL,
    actual_paid_ctc2 double precision,
    ctc numeric(18,2),
    ctc_paid_days double precision,
    ctc_actual_paid double precision,
    mobile_deduction double precision,
    salaryid integer NOT NULL,
    employeenpsrate double precision,
    employernpsrate double precision,
    insuranceamount double precision,
    familyinsuranceamount double precision,
    bankaccountno character varying(30) COLLATE pg_catalog."default",
    ifsccode character varying(30) COLLATE pg_catalog."default",
    bankname character varying(100) COLLATE pg_catalog."default",
    bankbranch character varying(200) COLLATE pg_catalog."default",
    netarear double precision,
    arearaddedmonths text COLLATE pg_catalog."default",
    employee_esi_incentive_deduction numeric,
    employer_esi_incentive_deduction numeric,
    total_esi_incentive_deduction numeric,
    salaryindaysopted character varying(1) COLLATE pg_catalog."default",
    salarydays integer,
    otherledgerarear double precision,
    otherledgerdeductions double precision,
    attendancemode text COLLATE pg_catalog."default",
    incrementarear integer,
    incrementarear_basic integer,
    incrementarear_hra integer,
    incrementarear_allowance integer,
    incrementarear_gross integer,
    incrementarear_employeeesi integer,
    incrementarear_employeresi integer,
    lwf_employee numeric(18,2),
    lwf_employer numeric(18,2),
    bonus double precision,
    otherledgerarearwithoutesi numeric,
    otherdeductions double precision,
    othervariables double precision,
    otherdeductionswithesi double precision,
    lwfstatecode integer,
    tdsadjustment numeric,
    atds double precision,
    hrgeneratedon text COLLATE pg_catalog."default",
    disbursedledgerids text COLLATE pg_catalog."default",
    security_amt double precision,
    issalaryorliability text COLLATE pg_catalog."default",
    professionaltax integer,
    customtaxablecomponents text COLLATE pg_catalog."default",
    customnontaxablecomponents text COLLATE pg_catalog."default",
    ratesalarybonus numeric,
    ratecommission numeric,
    ratetransport_allowance numeric,
    ratetravelling_allowance numeric,
    rateleave_encashment numeric,
    rateovertime_allowance numeric,
    ratenotice_pay numeric,
    ratehold_salary_non_taxable numeric,
    ratechildren_education_allowance numeric,
    rategratuityinhand numeric,
    salarybonus double precision,
    commission double precision,
    transport_allowance double precision,
    travelling_allowance double precision,
    leave_encashment double precision,
    overtime_allowance double precision,
    notice_pay double precision,
    hold_salary_non_taxable double precision,
    children_education_allowance double precision,
    gratuityinhand double precision,
    customeraccountid bigint,
    orgempcode character varying(20) COLLATE pg_catalog."default",
    tpcode character varying(40) COLLATE pg_catalog."default",
    verificationstatus character varying(30) COLLATE pg_catalog."default",
    hasarrear character varying(20) COLLATE pg_catalog."default",
    rejectstatus character varying(20) COLLATE pg_catalog."default",
    processedon character varying(11) COLLATE pg_catalog."default",
    paiddaysstatus character varying(10) COLLATE pg_catalog."default",
    pfpaystatus character varying(15) COLLATE pg_catalog."default",
    attendanceid bigint,
    jobtype character varying(50) COLLATE pg_catalog."default" DEFAULT 'NonUnit'::character varying,
    tea_allowance numeric(10,2) DEFAULT 0.0,
    unitname character varying(200) COLLATE pg_catalog."default",
    departmentname character varying(200) COLLATE pg_catalog."default",
    designationname character varying(200) COLLATE pg_catalog."default",
    pfapplicablecomponents numeric(18,2),
    esiapplicablecomponents numeric(18,2),
    isgroupinsurance character varying(1) COLLATE pg_catalog."default" DEFAULT 'N'::character varying,
    employerinsuranceamount numeric,
    advicelockstatus character varying(20) COLLATE pg_catalog."default",
    charity_contribution_amount numeric(18,2) DEFAULT 0.0,
    incentivepaiddays numeric(18,2) DEFAULT 0.0,
    paymentadvice_id integer NOT NULL DEFAULT nextval('paymentadvice_paymentadvice_id_seq'::regclass),
    mealvoucher numeric(10,2),
    multipayoutrequestid bigint NOT NULL DEFAULT 0,
    overtime numeric(18,2) DEFAULT 0,
    workflowappid bigint DEFAULT '-9999'::integer,
    is_workflow_approved character varying(1) COLLATE pg_catalog."default" DEFAULT 'Y'::character varying,
    salaryjson text COLLATE pg_catalog."default",
    otherearningcomponents numeric(18,2) DEFAULT 0.0,
    CONSTRAINT paymentadvice_pk PRIMARY KEY (emp_code, mprmonth, mpryear, salaryid, batch_no, multipayoutrequestid),
    CONSTRAINT paymentadvice_advicelockstatus_check CHECK (advicelockstatus::text = ANY (ARRAY['Locked'::character varying::text, 'Unlocked'::character varying::text, 'Rejected'::character varying::text])),
    CONSTRAINT paymentadvice_is_workflow_approved_check CHECK (is_workflow_approved::text = ANY (ARRAY['Y'::character varying, 'N'::character varying]::text[]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.paymentadvice
    OWNER to payrollingdb;
-- Index: idx_paymentadvice_uq1

-- DROP INDEX IF EXISTS public.idx_paymentadvice_uq1;

CREATE UNIQUE INDEX IF NOT EXISTS idx_paymentadvice_uq1
    ON public.paymentadvice USING btree
    (emp_code ASC NULLS LAST, mprmonth ASC NULLS LAST, mpryear ASC NULLS LAST, attendancemode COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default
    WHERE jobtype::text <> 'Unit Parameter'::text;
-- Index: idx_paymentadvice_uq2

-- DROP INDEX IF EXISTS public.idx_paymentadvice_uq2;

CREATE UNIQUE INDEX IF NOT EXISTS idx_paymentadvice_uq2
    ON public.paymentadvice USING btree
    (emp_code ASC NULLS LAST, attendanceid ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default
    WHERE jobtype::text = 'Unit Parameter'::text;

-- Trigger: trg_paymentadvice_history

-- DROP TRIGGER IF EXISTS trg_paymentadvice_history ON public.paymentadvice;

CREATE OR REPLACE TRIGGER trg_paymentadvice_history
    BEFORE DELETE OR UPDATE 
    ON public.paymentadvice
    FOR EACH ROW
    EXECUTE FUNCTION public.fn_paymentadvice();